-- Account-database baseline schema.
--
-- Loaded by `m0012_bootstrap.rs` whenever a new account database is opened
-- for the first time. Captures the per-account schema at the bootstrap's
-- BASELINE_VERSION, so new accounts skip replaying historical local
-- data-migration logic that only matters for accounts upgraded from older
-- installs (mirror of `global/fresh_schema.sql` for the local timeline).
--
-- Phase 18a/18b status: intentionally empty. `media_references` is
-- logically account-scoped but lives on the shared DB until
-- `AccountDatabase` is wired into production init (Phase 18c+). When
-- that wiring lands, add the `media_references` DDL here and create a
-- local migration to extract it from shared.
--
-- Rebaselining: when a future local migration does data extraction against
-- transient shared schema, consider rebaselining — bump
-- `BASELINE_VERSION` in `m0012_bootstrap.rs`, update this file to the
-- post-extraction schema, and add the now-skipped versions to
-- `STAMPED_PRIOR_LOCAL_VERSIONS`. New accounts then skip those locals
-- entirely instead of trying to replay them against shared state that may
-- have moved on.
